name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME2 }}
          password: ${{ secrets.DOCKERHUB_TOKEN2 }}
      - name: Build website image
        run: docker build --platform linux --tag violetmeow/taskapi:latest -f src/Dockerfile .
      - name: Publish website image
        run: docker push violetmeow/taskapi:latest

  deploy:
    name: Web App deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: App service auth
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cousin-api-test'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'violetmeow/taskapi:latest'

  slack:
    needs: [testing, build]
    runs-on: ubuntu-latest
    steps:
      - name: Notify success on Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'CI-CD Success Violet'
